version: "3"
services:
  # service configuration for our database
  database_tbilisi:

    # use the preferred version of the official Postgres image
    # see https://hub.docker.com/_/postgres/
    image: postgres:9.4.5

    # persist the database between containers by storing it in a volume
    volumes:
      - postgres_tbilisi:/var/lib/postgresql/data

  # service configuration for our dockerized Rails app
  app:

    # use the Dockerfile next to this file
    build: .
    entrypoint: /usr/local/bin/wait-for-it.sh database_tbilisi:5432 -- /usr/local/bin/entrypoint.sh
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    working_dir: /var/www/consul

    # rely on the RAILS_ENV value of the host machine
    env_file: .env

    # makes the app container aware of the DB container
    depends_on:
      - database_tbilisi

    # expose the port we configured Unicorn to bind to
    expose:
      - "3000"
    # map our application source code, in full, to the application root of our container
    volumes:
      - .:/var/www/consul:delegated
      - bundle:/usr/local/bundle:delegated
volumes:
  postgres_tbilisi: {}
  bundle: {}
networks:
  default:
    external:
      name: nginxproxy_default
